# Generated by Django 5.0.6 on 2024-06-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_remove_message_chat_alter_channel_owner_usermessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
    ]
